// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TaskHud","status":true,"description":"v1.4 任務顯示 HUD（右上角常駐，多行＋變數自動更新）","parameters":{"HudX":"0","HudY":"20","HudWidth":"340","HudHeight":"180","HudOpacity":"220","FontSizeTitle":"22","FontSizeBody":"20","TitleColor":"6"}},
{"name":"ForceStretch","status":true,"description":"強制網頁版遊戲自動延展填滿可用空間（適合 iframe / 平板橫向）","parameters":{}},
{"name":"PlayerLogger","status":true,"description":"玩家行為紀錄系統（本機寫檔 / 網頁 localStorage / 可匯出）v1.2","parameters":{}}
];
